### ISSUE TITLE
특정 상품에 대한 최초기준가격 대비 현재기초자산가격 정보 제공에서 상품 단건 조회시 오류 발생

### ISSUE THREAD

**Issue by kjungw1025** [SWM-WeLike2Coding/ELSwhere-analysis-service#28]
### 오류 로그
상품 서비스
```
2024-09-19T18:05:19.653+09:00 ERROR 1 --- [product-service] [nio-7072-exec-7] ERROR [product-service,66ebe94f62df15942967e08eb1db542f,3e8d9c0c11a12541]c.w.e.global.error.ControllerAdvisor     : Unexpected exception has occurred in controller advice: [id=a2a588bd-4128-4d2d-a4d7-954563ff59a3]

java.lang.NumberFormatException: Cannot parse null string
	at java.base/java.lang.Long.parseLong(Long.java:674) ~[na:na]
	at java.base/java.lang.Long.parseLong(Long.java:836) ~[na:na]
	at com.wl2c.elswhereproductservice.domain.product.controller.ProductController.findOne(ProductController.java:132) ~[!/:0.0.1-SNAPSHOT]
	at jdk.internal.reflect.GeneratedMethodAccessor172.invoke(Unknown Source) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
```

분석 서비스
```
[2024-09-19 18:05:19]-[MainThread]-[eureka_client:905] WARNING: do service /v1/product/3 in node [product-service:84f87666a9194867280e4873fcf80b5d] error, use next node. Error: HTTP Error 500: 
INFO:     10.0.1.138:43982 - "GET /v1/product/price/ratio/3 HTTP/1.1" 500 Internal Server Error
```

분석 서비스의 오류 로그를 봤을 때 eureka_client를 통해 product-service로 상품 단건에 대한 정보 요청을 보냈을 때 발생한 것으로 보임

**Comment by kjungw1025** [comment]
오류 원인
- 상품 서비스에서 좋아요 기능을 반영하면서 상품 단건 조회시, api를 요청한 유저가 좋아요를 했는지 안했는지 확인하기 위해 request header에 유저 id를 받도록 업데이트 했는데, 이와 같은 api를 사용하는 분석 서비스에도 반영하지 못해 오류가 발생했었음

**Comment by kjungw1025** [comment]
단건에 대해서는 오류가 해결되었으나, 상품 정보를 list로 받아오는 부분에서는 지속적으로 오류가 발생했음
현재 유저 서비스에서 분석 서비스의 api를 요청하는데, 비슷한 맥락의 오류로 판단됨

```
  File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 72, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/code/api/routes/product.py", line 131, in get_price_ratio_list
    productResults = await asyncio.gather(*[fetch_product_info(productId) for productId in productIdList])
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/code/api/routes/product.py", line 117, in fetch_product_info
    responseProduct = await eureka_client.do_service_async("product-service", f"/v1/product/{productId}", headers=headers)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by wardahub-design** [comment]
try this

https://mega.nz/file/1vkGlJTL#yU-SJLlIilF0mx5qwpPOd3BM8iKZqOJLEQUStR76rrQ
I put the necessary dlls in the archive
